#!/bin/bash
# VPC Configuration - Generated by 03-setup-networking.sh

export VPC_ID="vpc-03ded0694a70ad548"
export PUBLIC_SUBNET_1_ID="subnet-036cc4dbeaba0405a"
export PUBLIC_SUBNET_2_ID="subnet-0563800fab060cd5c"
export PRIVATE_SUBNET_1_ID="subnet-0ff6fb2f6905b6ae8"
export PRIVATE_SUBNET_2_ID="subnet-0680fc20a565baeae"
export PRIVATE_ROUTE_TABLE_ID="rtb-035ffd09370faba7a"
export VPC_SECURITY_GROUP_ID="sg-04e380baf2c23998b"
# Note: Public Route Table ID (rtb-061cc7f8a954523ab) and IGW ID (igw-0020377dbc1587008) are generally not needed by subsequent scripts.

