#!/bin/bash

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"

# Source all the configuration files
source "$SCRIPT_DIR/01-setup-variables.sh"
source "$SCRIPT_DIR/vpc-config.sh"
source "$SCRIPT_DIR/rds-config.sh"
source "$SCRIPT_DIR/alb-config.sh"

echo "==============================================================="
echo "Deployment Summary for ${APP_NAME}"
echo "==============================================================="
echo ""
echo "Your application is now deployed at: https://${SUBDOMAIN}.${DOMAIN_NAME}"
echo "(Note: DNS propagation may take some time)"
echo ""
echo "Architecture Overview:"
echo "---------------------"
echo "Region: $AWS_REGION"
echo "VPC ID: $VPC_ID"
echo "Public Subnets: $PUBLIC_SUBNET_1_ID, $PUBLIC_SUBNET_2_ID"
echo "Private Subnets: $PRIVATE_SUBNET_1_ID, $PRIVATE_SUBNET_2_ID"
echo ""
echo "Database Information:"
echo "--------------------"
echo "RDS Instance: ${APP_NAME}-db"
echo "Endpoint: $DB_ENDPOINT"
echo "Port: $DB_PORT"
echo "Username: $DB_USERNAME"
echo "Database Name: $DB_NAME"
echo "Password: Stored locally in AWS Secrets Manager"
echo ""
echo "Application Resources:"
echo "--------------------"
echo "ECS Cluster: ${APP_NAME}-cluster"
echo "ECS Service: ${APP_NAME}-service"
echo "Load Balancer: ${APP_NAME}-alb ($ALB_DNS_NAME)"
echo "ECR Repository: ${APP_NAME}"
echo ""
echo "Important URLs:"
echo "--------------"
echo "Application URL: https://${SUBDOMAIN}.${DOMAIN_NAME}"
echo "Health Endpoint: https://${SUBDOMAIN}.${DOMAIN_NAME}/api/health"
echo ""
echo "Useful Commands:"
echo "--------------"
echo "Check running tasks: aws ecs list-tasks --cluster ${APP_NAME}-cluster --region $AWS_REGION"
echo "Check service status: aws ecs describe-services --cluster ${APP_NAME}-cluster --services ${APP_NAME}-service --region $AWS_REGION"
echo "Check RDS status: aws rds describe-db-instances --db-instance-identifier ${APP_NAME}-db --region $AWS_REGION"
echo ""
echo "Monitoring and Maintenance:"
echo "-------------------------"
echo "- Application logs can be found in AWS CloudWatch Logs under the /ecs/${APP_NAME} log group"
echo "- Adjust task count for scaling: aws ecs update-service --cluster ${APP_NAME}-cluster --service ${APP_NAME}-service --desired-count N --region $AWS_REGION"
echo "- Update application: Build and push a new Docker image, then update the service"
echo ""
echo "Deployment complete! Thank you for using the AWS deployment script."
echo "===============================================================" 