# AWS Configuration
$AWS_REGION = "eu-west-1"
$APP_NAME = "feature-poll"
$DOMAIN_NAME = "murrdev.com"
$SUBDOMAIN = "feature-poll"

# Database Configuration
$DB_NAME = "feature_poll"
$DB_USERNAME = "dbadmin"
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$bytes = New-Object byte[] 32
$rng.GetBytes($bytes)
$DB_PASSWORD = [Convert]::ToBase64String($bytes)
$DB_INSTANCE_CLASS = "db.t3.micro"
$DB_ENGINE = "postgres"
$DB_ENGINE_VERSION = "13"
$DB_ALLOCATED_STORAGE = "20"

# VPC Configuration
$VPC_CIDR = "10.0.0.0/16"
$PUBLIC_SUBNET_1_CIDR = "10.0.1.0/24"
$PUBLIC_SUBNET_2_CIDR = "10.0.2.0/24"
$PRIVATE_SUBNET_1_CIDR = "10.0.3.0/24"
$PRIVATE_SUBNET_2_CIDR = "10.0.4.0/24"

# ECR Configuration
$ECR_REPOSITORY_NAME = "${APP_NAME}-repo"

# ECS Configuration
$ECS_CLUSTER_NAME = "${APP_NAME}-cluster"
$ECS_SERVICE_NAME = "${APP_NAME}-service"
$ECS_TASK_FAMILY = "${APP_NAME}-task"
$ECS_CONTAINER_NAME = "${APP_NAME}-container"
$ECS_CONTAINER_PORT = "3000"
$ECS_TASK_CPU = "256"
$ECS_TASK_MEMORY = "512"
$ECS_SERVICE_COUNT = "1"

# Load Balancer Configuration
$ALB_NAME = "${APP_NAME}-alb"
$ALB_TG_NAME = "${APP_NAME}-tg"

# SSL Configuration
$SSL_CERTIFICATE_ARN = ""
$HOSTED_ZONE_ID = ""

# Export all variables
$env:AWS_REGION = $AWS_REGION
$env:APP_NAME = $APP_NAME
$env:DOMAIN_NAME = $DOMAIN_NAME
$env:SUBDOMAIN = $SUBDOMAIN
$env:DB_NAME = $DB_NAME
$env:DB_USERNAME = $DB_USERNAME
$env:DB_PASSWORD = $DB_PASSWORD
$env:DB_INSTANCE_CLASS = $DB_INSTANCE_CLASS
$env:DB_ENGINE = $DB_ENGINE
$env:DB_ENGINE_VERSION = $DB_ENGINE_VERSION
$env:DB_ALLOCATED_STORAGE = $DB_ALLOCATED_STORAGE
$env:VPC_CIDR = $VPC_CIDR
$env:PUBLIC_SUBNET_1_CIDR = $PUBLIC_SUBNET_1_CIDR
$env:PUBLIC_SUBNET_2_CIDR = $PUBLIC_SUBNET_2_CIDR
$env:PRIVATE_SUBNET_1_CIDR = $PRIVATE_SUBNET_1_CIDR
$env:PRIVATE_SUBNET_2_CIDR = $PRIVATE_SUBNET_2_CIDR
$env:ECR_REPOSITORY_NAME = $ECR_REPOSITORY_NAME
$env:ECS_CLUSTER_NAME = $ECS_CLUSTER_NAME
$env:ECS_SERVICE_NAME = $ECS_SERVICE_NAME
$env:ECS_TASK_FAMILY = $ECS_TASK_FAMILY
$env:ECS_CONTAINER_NAME = $ECS_CONTAINER_NAME
$env:ECS_CONTAINER_PORT = $ECS_CONTAINER_PORT
$env:ECS_TASK_CPU = $ECS_TASK_CPU
$env:ECS_TASK_MEMORY = $ECS_TASK_MEMORY
$env:ECS_SERVICE_COUNT = $ECS_SERVICE_COUNT
$env:ALB_NAME = $ALB_NAME
$env:ALB_TG_NAME = $ALB_TG_NAME
$env:SSL_CERTIFICATE_ARN = $SSL_CERTIFICATE_ARN
$env:HOSTED_ZONE_ID = $HOSTED_ZONE_ID 