# GitHub Actions Workflow for Building and Deploying to AWS ECS

name: Deploy to AWS ECS

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: read # Needed to check out the repository
  # id-token: write # Required for AWS OIDC - Not needed if using access keys

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    # Removed outputs section

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image # Add ID back to reference image tag
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          # Save image URI to a file
          echo "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" > image-uri.txt

      - name: Upload image URI artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-artifact
          path: image-uri.txt

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build-and-push # Ensure build job completes first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download image URI artifact
        uses: actions/download-artifact@v4
        with:
          name: image-artifact
          # path defaults to workspace root

      - name: Read image URI from file
        id: image-uri-step
        run: echo "image_uri=$(cat image-uri.txt)" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_FAMILY }} --query taskDefinition > task-definition.json

      # Removed Debug Print Image Output step

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: feature-poll-app-container
          image: ${{ steps.image-uri-step.outputs.image_uri }} # Use output from reading the file

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: feature-poll-app-service
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
